config/routes.rb
Rails.application.routes.draw do
  root 'bus_delay#index'
  get '/trips' => 'trips#index'
  get '/traffic_delay' => 'bus_delay#traffic_delay'
  get '/data_quality' => 'bus_delay#data_quality'
  get '/stops' => 'bus_delay#stops'
  get '/trips/:trip_id' => 'trips#show'
  get '/trips/:trip_id/snapshot' => 'snapshot#show'
  get '/trips/:trip_id/snapshot/data' => 'snapshot#show_ajax'
  get '/trips/:trip_id/bus_interval' => 'bus_interval#index'
  get '/trips/:trip_id/bus_interval/data' => 'bus_interval#data'
  get '/trips/:trip_id/bus_interval/trips' => 'bus_interval#trips'
  get '/trips/:trip_id/bus_interval/statistics' => 'bus_interval#statistics'
  get '/trips/:trip_id/freq_dispatch/data' => 'freq_dispatch#data'
  get '/summary' => 'summary#index'
  get '/summary/data' => 'summary#data'
  get '/about' => 'about#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/bus_delay_controller.rb
class BusDelayController < ApplicationController
  def index
  end

  def traffic_delay
    travels = params["travels"] || 50
    limit = params["limit"] || 10
    @delays = BusInterval.mean_traffic_delay_by_trip(travels, limit)
    respond_to do |format|
      format.json {render :json => @delays, status: 200}
    end
  end

  def data_quality
    quality = {}
    DataQuality.all.each do |data|
     quality[data.name] = data.count
    end
    respond_to do |format|
      format.json {render :json => quality, status: 200}
    end
  end
  
  def stops
    stops = Stop.exists(statistics: true).pluck("loc.lat", "loc.lng", "statistics.avg")
    stops_array = []
    stops.each do |stop|
      next if stop[2]["avg"].nil?
      temp = []
      temp << stop[0]["lat"]
      temp << stop[1]["lng"]
      temp << stop[2]["avg"]
      stops_array << temp
    end
    respond_to do |format|
      format.json {render :json => stops_array, status: 200}
    end
  end
end

app/helpers/bus_delay_helper.rb
module BusDelayHelper
end

app/views/bus_delay/index.html.erb
<script>
$( document ).ready(function() {
  createHeatMap();
});
</script>

<script>
  plotGeneralDashboard();
  plotSummaryDispatch();
</script>

<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell mdl-cell--8-col mdl-typography--text-center">
    <h1>
      Bus Delay Analytical System
    </h1>
  </div>
  <div class="mdl-layout-spacer"></div>
</div>

<div class="mdl-grid demo-content">
  <div class="main-charts mdl-color--white mdl-shadow--2dp mdl-cell mdl-cell--12-col mdl-grid">
    <div class="mdl-cell mdl-cell--6-col">
      <div id="traffic_delay_chart_div" style="width: 100%; height: 250px;"></div>
    </div>
    <div class="mdl-cell mdl-cell--3-col">
      <div id="fulfill" style="width: 100%; height: 250px;"></div>
    </div>
    <div class="mdl-cell mdl-cell--3-col">
      <div id="not_fulfill" style="width: 100%; height: 250px;"></div>
    </div>
  </div>
  <div class="secondary-data mdl-shadow--2dp mdl-color--white mdl-cell mdl-cell--8-col">
    <div id="map"></div>
  </div>
  <div class="demo-cards mdl-cell mdl-cell--4-col mdl-cell--8-col-tablet mdl-grid mdl-grid--no-spacing">
    <div class="demo-updates mdl-card mdl-shadow--2dp mdl-cell mdl-cell--4-col mdl-cell--4-col-tablet mdl-cell--12-col-desktop">
      <div class="mdl-card__title mdl-card--expand mdl-color--pink-400">
        <h2 class="mdl-card__title-text" style="color: white">Search Bus Trips</h2>
      </div>
      <div class="mdl-card__supporting-text mdl-color-text--indigo-600 mdh-expandable-search home-search mdl-typography--text-center">
        <i class="material-icons">search</i>
        <%= form_tag(trips_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search", size: 1, class: "mdl-textfield__input" %>
        <% end %>
      </div>
      <div class="mdl-card__actions mdl-card--border">
        <a href="/trips" class="mdl-button mdl-js-button mdl-js-ripple-effect">All Trips</a>
      </div>
    </div>
    <div class="demo-separator mdl-cell--1-col"></div>
    <div class="demo-options mdl-card mdl-color--white mdl-shadow--2dp mdl-cell mdl-cell--4-col mdl-cell--3-col-tablet mdl-cell--12-col-desktop">
      <div class="mdl-card__title mdl-card--expand mdl-color--grey-400">
        <h2 class="mdl-card__title-text" style="color: white">Trips Monitoring - Quality of Data</h2>
      </div>
        <div id="data_quality__chart_div" style="width: 100%; height: 350px;"></div>
      </div>
    </div>
  </div>
</div>